plugins {
  id 'java-library'
}

dependencies {
  api project(':momentum-gfx')
  api project(':momentum-math')

  compileOnly "org.lwjgl:lwjgl:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-opengl:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-shaderc:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-spvc:${lwjgl_version}"
}
