plugins {
  id 'java-library'
}

dependencies {
  api project(':fmhi-gfx')
  compileOnly 'org.jspecify:jspecify:1.0.0'

  compileOnly "org.lwjgl:lwjgl:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-opengl:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-shaderc:${lwjgl_version}"
  compileOnly "org.lwjgl:lwjgl-spvc:${lwjgl_version}"

  implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
  implementation 'org.apache.logging.log4j:log4j-api:2.25.4'
}
