plugins {
  id 'java-library'
}

dependencies {
  api project(':fmhi-core')
  api project(':fmhi-codec')

  compileOnly "org.lwjgl:lwjgl:${lwjgl_version}"
  implementation "org.lwjgl:lwjgl-freetype:${lwjgl_version}"
  implementation "org.lwjgl:lwjgl-harfbuzz:${lwjgl_version}"

  implementation 'com.ibm.icu:icu4j:76.1'
}
