plugins {
  id 'java-library'
}

dependencies {
  api project(':momentum-core')
  api project(':momentum-codec')
  api project(':momentum-event')
  api project(':momentum-input')
  api project(':momentum-math')

  compileOnly "org.lwjgl:lwjgl:${lwjgl_version}"
  implementation "org.lwjgl:lwjgl-freetype:${lwjgl_version}"
  implementation "org.lwjgl:lwjgl-harfbuzz:${lwjgl_version}"

  implementation 'com.ibm.icu:icu4j:76.1'
}
